import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import { Provider } from "react-redux";

import "./globals.css";
import NavBarWrapper from "@/components/NavBarWrapper";

import StyledComponentsRegistry from "@/lib/registry";

import { DataProvider } from "@/context/burgerData";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <DataProvider>
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <NavBarWrapper />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
    // </DataProvider>
  );
}
